# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: random_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'random_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14random_service.proto\"\xbb\x01\n\x13RandomNumberRequest\x12\x0b\n\x03min\x18\x01 \x01(\x05\x12\x0b\n\x03max\x18\x02 \x01(\x05\x12\x11\n\x04seed\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05\x63ount\x18\x04 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x06unique\x18\x05 \x01(\x08H\x02\x88\x01\x01\x12\x1c\n\x0foutput_duration\x18\x06 \x01(\x08H\x03\x88\x01\x01\x42\x07\n\x05_seedB\x08\n\x06_countB\t\n\x07_uniqueB\x12\n\x10_output_duration\"l\n\x14RandomNumberResponse\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\x12\x1c\n\x0foutput_duration\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\tseed_used\x18\x03 \x01(\x05\x42\x12\n\x10_output_duration2\\\n\x13RandomNumberService\x12\x45\n\x14GenerateRandomNumber\x12\x14.RandomNumberRequest\x1a\x15.RandomNumberResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'random_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANDOMNUMBERREQUEST']._serialized_start=25
  _globals['_RANDOMNUMBERREQUEST']._serialized_end=212
  _globals['_RANDOMNUMBERRESPONSE']._serialized_start=214
  _globals['_RANDOMNUMBERRESPONSE']._serialized_end=322
  _globals['_RANDOMNUMBERSERVICE']._serialized_start=324
  _globals['_RANDOMNUMBERSERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
