# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import random_service_pb2 as random__service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in random_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RandomNumberServiceStub(object):
    """The random number service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateRandomNumber = channel.unary_unary(
                '/RandomNumberService/GenerateRandomNumber',
                request_serializer=random__service__pb2.RandomNumberRequest.SerializeToString,
                response_deserializer=random__service__pb2.RandomNumberResponse.FromString,
                _registered_method=True)


class RandomNumberServiceServicer(object):
    """The random number service definition.
    """

    def GenerateRandomNumber(self, request, context):
        """Generates a random number
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RandomNumberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateRandomNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRandomNumber,
                    request_deserializer=random__service__pb2.RandomNumberRequest.FromString,
                    response_serializer=random__service__pb2.RandomNumberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RandomNumberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RandomNumberService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RandomNumberService(object):
    """The random number service definition.
    """

    @staticmethod
    def GenerateRandomNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RandomNumberService/GenerateRandomNumber',
            random__service__pb2.RandomNumberRequest.SerializeToString,
            random__service__pb2.RandomNumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
